export const EMPRESAS = ["LESSUL", "MS_DECOR", "VIVA_VIDA", "MOVELBENTO", "MODIFIKA"] as const;
export const STATUS_RECLAMACAO = ["AFETANDO", "NAO_AFETANDO", "REMOVIDA"] as const;
export const MOTIVOS = [
  "DESISTENCIA",
  "DEFEITO_FABRICACAO",
  "PRODUTO_INCORRETO",
  "FALTANDO_ITENS",
  "PRODUTO_DANIFICADO",
  "PROBLEMA"
] as const;
export const STATUS_TICKET = [
  "CONCLUIDO",
  "ABERTO",
  "AGUARDANDO_CLIENTE",
  "AGUARDANDO_DEVOLUCAO",
  "AGUARDANDO_ASSISTENCIA",
  "AGUARDANDO_MARKETPLACE"
] as const;
