import { StatusOperacional, Empresa, Prisma } from "@prisma/client";
import Link from "next/link";
import { getCurrentUser } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { formatEnumLabel } from "@/lib/formatters/display";
import { EMPRESAS } from "@/config/domains";
import { OperationalRequestsPanel } from "@/components/loja/operational-requests-panel";

type PageProps = {
  searchParams: Promise<{
      empresa?: string;
          status?: string;
            }>;
            };

            type EmpresaValue = (typeof EMPRESAS)[number];

            type OperationalRequestWithTicket= {
              id: string;
                empresa: Empresa;
                  ticketId: string;
                    tipoAcao: string;
                      status: StatusOperacional;
                        prazoOperacional: Date | null;
                          updatedAt: Date;
                            comentarioLoja: string | null;
                              comentarioAtendente: string | null;
                                codigoRastreio: string | null;
                                  valorReembolso: unknown;
                                    valorColetaEnvioPecas: unknown;
                                      ticket: {
                                          nomeCliente: string;
                                              numeroVenda: string;
                                                  linkPedido: string | null;
                                                      anexoUrl: string | null;
                                                          anexoNome: string | null;
                                                              anexoPath: string | null;
                                                                };
                                                                };

                                                                // Usa diretamente os status gerados pelo Prisma.
                                                                // Assim a página nunca fica com status divergente do schema.prisma.
                                                                const statusOptions = Object.values(StatusOperacional) as StatusOperacional[];

                                                                const statusLabel: Record<string, string> = {
                                                                  EM_ABERTO: "Em aberto",
                                                                    ASSISTENCIA_A_CAMINHO: "Assistência a caminho",
                                                                      ASSISTENCIA_ENTREGUE: "Assistência entregue",
                                                                        COLETA_SOLICITADA: "Coleta solicitada",
                                                                          COLETA_FEITA: "Coleta feita",
                                                                            DEVOLUCAO_SOLICITADA: "Devolução solicitada",
                                                                              DEVOLUCAO_A_CAMINHO: "Devolução a caminho",
                                                                                DEVOLUCAO_REALIZADA: "Devolução realizada",
                                                                                  REEMBOLSO_PENDENTE: "Reembolso pendente",
                                                                                    REEMBOLSO_REALIZADO: "Reembolso realizado",
                                                                                      AGUARDANDO_ATENDENTE: "Aguardando atendente",
                                                                                        CONCLUIDA: "Concluídas"
                                                                                        };

                                                                                        function isEmpresa(value: string | undefined): value is EmpresaValue {
                                                                                          return Boolean(value && EMPRESAS.includes(value as EmpresaValue));
                                                                                          }

                                                                                          function isStatusOperacional(value: string | undefined): value is StatusOperacional {
                                                                                            return Boolean(value && statusOptions.includes(value as StatusOperacional));
                                                                                            }

                                                                                            function toNumber(value: unknown): number {
                                                                                              if (value === null || value === undefined || value === "") return 0;

                                                                                                if (typeof value === "number") {
                                                                                                    return Number.isFinite(value) ? value : 0;
                                                                                                      }

                                                                                                        if (typeof value === "string") {
                                                                                                            const parsed = Number(value.replace(",", "."));
                                                                                                                return Number.isFinite(parsed) ? parsed : 0;
                                                                                                                  }

                                                                                                                    if (typeof value === "object" && value !== null && "toNumber" in value) {
                                                                                                                        const parsed = (value as { toNumber: () => number }).toNumber();
                                                                                                                            return Number.isFinite(parsed) ? parsed : 0;
                                                                                                                              }

                                                                                                                                const parsed = Number(value);
                                                                                                                                  return Number.isFinite(parsed) ? parsed : 0;
                                                                                                                                  }

                                                                                                                                  export default async function LojaSolicitacoesPage({ searchParams }: PageProps) {
                                                                                                                                    const user = await getCurrentUser();

                                                                                                                                      if (user.perfil !== "LOJA" && user.perfil !== "ADMIN") {
                                                                                                                                          redirect("/dashboard");
                                                                                                                                            }

                                                                                                                                              const params = await searchParams;

                                                                                                                                                const empresaFiltro = isEmpresa(params.empresa) ? params.empresa : undefined;
                                                                                                                                                  const statusFiltro = isStatusOperacional(params.status) ? params.status : undefined;

                                                                                                                                                    const baseWhere: Prisma.OperationalRequestWhereInput =
                                                                                                                                                        user.perfil === "LOJA"
                                                                                                                                                              ? { empresa: user.empresaVinculada ?? undefined }
                                                                                                                                                                    : empresaFiltro
                                                                                                                                                                            ? { empresa: empresaFiltro as Empresa }
                                                                                                                                                                                    : {};

                                                                                                                                                                                      const where: Prisma.OperationalRequestWhereInput = {
                                                                                                                                                                                          ...baseWhere,
                                                                                                                                                                                              ...(statusFiltro ? { status: statusFiltro } : {})
                                                                                                                                                                                                };

                                                                                                                                                                                                  const data = (await prisma.operationalRequest.findMany({
                                                                                                                                                                                                      where,
                                                                                                                                                                                                          include: {
                                                                                                                                                                                                                ticket: {
                                                                                                                                                                                                                        select: {
                                                                                                                                                                                                                                  nomeCliente: true,
                                                                                                                                                                                                                                            numeroVenda: true,
                                                                                                                                                                                                                                                      linkPedido: true,
                                                                                                                                                                                                                                                                anexoUrl: true,
                                                                                                                                                                                                                                                                          anexoNome: true,
                                                                                                                                                                                                                                                                                    anexoPath: true
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                          orderBy: {
                                                                                                                                                                                                                                                                                                                updatedAt: "desc"
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                      })) as unknown as OperationalRequestWithTicket[];

                                                                                                                                                                                                                                                                                                                        const statusStats = statusOptions.reduce(
                                                                                                                                                                                                                                                                                                                            (acc, status) => {
                                                                                                                                                                                                                                                                                                                                  acc[status] = data.filter((d) => d.status === status).length;
                                                                                                                                                                                                                                                                                                                                        return acc;
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                {} as Record<StatusOperacional, number>
                                                                                                                                                                                                                                                                                                                                                  );

                                                                                                                                                                                                                                                                                                                                                    const atrasadas = data.filter(
                                                                                                                                                                                                                                                                                                                                                        (d) => d.prazoOperacional && d.prazoOperacional < new Date() && d.status !== "CONCLUIDA"
                                                                                                                                                                                                                                                                                                                                                          ).length;

                                                                                                                                                                                                                                                                                                                                                            const stats = [
                                                                                                                                                                                                                                                                                                                                                                ...statusOptions.map((status) => ({
                                                                                                                                                                                                                                                                                                                                                                      key: status,
                                                                                                                                                                                                                                                                                                                                                                            label: statusLabel[status] ?? formatEnumLabel(status),
                                                                                                                                                                                                                                                                                                                                                                                  value: statusStats[status]
                                                                                                                                                                                                                                                                                                                                                                                      })),
                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                key: "ATRASADAS",
                                                                                                                                                                                                                                                                                                                                                                                                      label: "Atrasadas",
                                                                                                                                                                                                                                                                                                                                                                                                            value: atrasadas
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                  ];

                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                        <section className="page">
                                                                                                                                                                                                                                                                                                                                                                                                                              <h1>Solicitações da Loja</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="panel" style={{ marginBottom: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <form
                                                                                                                                                                                                                                                                                                                                                                                                                                                      action="/loja/solicitacoes"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                method="get"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{ display: "flex", flexWrap: "wrap", gap: 12, alignItems: "flex-end" }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {user.perfil === "ADMIN" ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label style={{ minWidth: 220 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Empresa
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <select name="empresa" defaultValue={empresaFiltro ?? ""}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <option value="">Todas as empresas</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {EMPRESAS.map((emp) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option key={emp} value={emp}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {formatEnumLabel(emp)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : null}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <label style={{ minWidth: 260 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Status operacional
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select name="status" defaultValue={statusFiltro ?? ""}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">Todos os status</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {statusOptions.map((status) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option key={status} value={status}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {statusLabel[status] ?? formatEnumLabel(status)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="btn btn-primary" type="submit">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Filtrar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link className="btn btn-secondary" href="/loja/solicitacoes">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Limpar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid" style={{ gridTemplateColumns: "repeat(4,minmax(0,1fr))" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {stats.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <article className="card" key={item.key}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <strong>{item.label}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: 24 }}>{item.value}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <OperationalRequestsPanel
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        perfil={user.perfil}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data={data.map((row) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          id: row.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    empresa: row.empresa,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ticketId: row.ticketId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tipoAcao: row.tipoAcao,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: row.status,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            prazoOperacional: row.prazoOperacional?.toISOString() ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updatedAt: row.updatedAt.toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                comentarioLoja: row.comentarioLoja ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          comentarioAtendente: row.comentarioAtendente ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    codigoRastreio: row.codigoRastreio ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              valorReembolso: toNumber(row.valorReembolso),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        valorColetaEnvioPecas: toNumber(row.valorColetaEnvioPecas),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ticket: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              nomeCliente: row.ticket.nomeCliente,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          numeroVenda: row.ticket.numeroVenda,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      linkPedido: row.ticket.linkPedido ?? null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          anexo: row.ticket.anexoUrl
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ? {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fileUrl: row.ticket.anexoUrl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fileName: row.ticket.anexoNome ?? "Anexo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      filePath: row.ticket.anexoPath ?? null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : undefined
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
