CREATE TYPE "StatusOperacionalLoja" AS ENUM (
  'EM_ABERTO',
  'ASSISTENCIA_ENVIADA',
  'ASSISTENCIA_A_CAMINHO',
  'ASSISTENCIA_ENTREGUE',
  'COLETA_SOLICITADA',
  'COLETA_FEITA',
  'DEVOLUCAO_SOLICITADA',
  'DEVOLUCAO_A_CAMINHO',
  'DEVOLUCAO_REALIZADA',
  'REEMBOLSO_PENDENTE',
  'REEMBOLSO_REALIZADO',
  'AGUARDANDO_ATENDENTE',
  'CONCLUIDA'
);

ALTER TABLE "Ticket"
ADD COLUMN "statusOperacionalLoja" "StatusOperacionalLoja" NOT NULL DEFAULT 'EM_ABERTO',
ADD COLUMN "codigoRastreio" TEXT,
ADD COLUMN "valorAssistencia" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "valorColetaEnvioPecas" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "comentarioLoja" TEXT;
